### ISSUE TITLE
Misprinted characters on demo page (unicode issue?)

### ISSUE THREAD

**Issue by ian2000611** [BigIroh/JooDee#1]
When viewing the demo page in Chrome there were several misprinted characters in the section of the page from news.ycombinator.com

Characters such as a long dash that were a multibyte character on the original page were sent to the client as a series of single byte characters.  I don't know if this is a problem with JooDee, or with Node.js but it would be nice if it could be fixed easily.

**Comment by ian2000611** [comment]
I just looked at the headers and the source...

Changing line 261 of joodee.js from 
    res.setHeader("Content-Type", "text/html");
to
    res.setHeader("Content-Type", "text/html; charset=utf8");
fixed the issue.

**Comment by mako-taco** [comment]
thanks a lot.  applied your change this morning.  good catch
